/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diffrentiation;

/**
 *
 * @author Winodw 7
 */
public class Diffrentiate extends javax.swing.JFrame {

    /**
     * Creates new form Determinates
     */
    public Diffrentiate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Diffrantiate");

        jButton2.setText("Another go");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void chai_rule(String io){
    //System.out.println();
    String s=io.replaceAll(" ","");
int x=s.length();
int t=0;

for(int i=0;i<x;i++){
    if(s.charAt(i)=='i' || s.charAt(i)=='c' || s.charAt(i)=='t' || s.charAt(i)=='l'){
        t++;
    }
}
int d=0;

for(int i=0;i<x;i++){
    if(d<=t){
         if(s.charAt(i)=='s'){if(s.charAt(i+1)=='i'){if(s.charAt(i+2)=='n')System.out.print("cos"+s.substring(i+3,x));d++;}}
        if(s.charAt(i)=='c'){if(s.charAt(i+1)=='o'){if(s.charAt(i+2)=='s')System.out.print("(-)sin"+s.substring(i+3,x));d++;}}
        if(s.charAt(i)=='t'){if(s.charAt(i+1)=='a'){if(s.charAt(i+2)=='n')System.out.print("sec^2"+s.substring(i+3,x));d++;}}
        if(s.charAt(i)=='l' && s.charAt(i+1)=='o' && s.charAt(i+2)=='g'){System.out.print("1/"+s.substring(i+3,x));d++;}
}
}
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String io=jTextField1.getText();
System.out.println();
int iolo=0;
//System.out.println(io.length()+"ccc"+io.substring(0,3));
for(int i=0;i<io.length();i++){
    if(io.charAt(i)=='+' || io.charAt(i)=='+'){
        iolo++;
    }
}
if(iolo!=0){
    try{
        String val=jTextField1.getText();
int t=0;
for(int i=0;i<val.length();i++){
    if(val.charAt(i)=='+' || val.charAt(i)=='-'){
        t++;
    }
}
int[] k=new int[t];
String[] kl=new String[t+1];
int n=0;
for(int i=0;i<val.length();i++){
    if(val.charAt(i)=='+' || val.charAt(i)=='-'){
       
        k[n]=i;
        n++;
    }
 }

//
//for(int i=0;i<k.length;i++){
//    System.out.println(k[i]);
//}

//
//int no=0;
//for(int i=0;i<kl.length;i++){
//    if(i==kl.length-1){
//        kl[i]=val.substring(no,val.length()-1);
//    }
//    kl[i]=val.substring(no,k[i]);
//    no=k[i]+1;
//}

if(t==1){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1));
}
if(t==2){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1));
}
if(t==3){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1,k[2]));
    System.out.print(val.charAt(k[2]));
    chai_rule(val.substring(k[2]+1));
}
if(t==4){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1,k[2]));
    System.out.print(val.charAt(k[2]));
    chai_rule(val.substring(k[2]+1,k[3]));
    System.out.print(val.charAt(k[3]));
    chai_rule(val.substring(k[3]+1));
}
//
//int no=0;
//for(int i=0;i<kl.length;i++){
//    kl[i]=val.substring(no,k[i]);
//    no=k[i]+1;
//    if(i==kl.length-1){
//    kl[i]=val.substring(k[i-1]+1);
//    //System.out.print("t"+t+"i"+i);
//    }
//}
//System.out.println("lets dee");

}
catch(Exception e){
    System.out.println(""+e);
}

}
else{
    chai_rule(io);
}



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/*String io=jTextField1.getText();
String s=io.replaceAll(" ","");
int length=s.length();int operator=1;
for(int i=0;i<length;i++){
    if(s.charAt(i)=='+' || s.charAt(i)=='-' || s.charAt(i)=='/' || s.charAt(i)=='*'){
        operator++;
    }
}int t=1;
String str[]={};int value_store[]={};
for(int i=0;i<length;i++){
    if(s.charAt(i)=='+' || s.charAt(i)=='-' || s.charAt(i)=='/' || s.charAt(i)=='*'){
        value_store[t]=i;
    }
}*/

/*
    int t=0;    String val=jTextField1.getText();
    int n=0;Object c;
for(int i=1;i<=val.length();i++){
    t++;
}/*
        String[] valu=val.split("[-+")
for(String a:valu){
 //   System.out.println(a);
    valu[n]=a;n++;
    for(int i=1;i<=t;i++){
        System.out.println(valu[i]);
    }
}
try{
int t=0;
String val=jTextField1.getText();
for(int i=0;i<val.length();i++){
    if(val.charAt(i)=='+' || val.charAt(i)=='-'){
        ++t;
    }
}
System.out.println(t);
int nk=0;
int no=0;
int[] k=new int[t];
String[] value=new String[t];
for(int ln=0;ln<val.length();ln++){
    if(val.charAt(ln)=='+' || val.charAt(ln)=='-'){
        //System.out.println(ln+" nk value"+nk);
        k[nk]=ln;
        //System.out.println(k[nk]);
        //value[nk]=val.substring(no,ln);
        nk++;
       
        //no=ln+1;
    }
    
    
    
   //System.out.println(nk);
}
//k[1]=(int)val.length();
System.out.println(k[0]+" "+k[1]+" here it finsies");

for(int i=0;i<=value.length-1;i++){
    value[i]=val.substring(no,k[i]);
    no=k[i]+1;
}
System.out.println(value[0]+" hk "+value[1]);

for(int i=0;i<=value.length-1;i++){
  System.out.println(value[i]);*/
try{
        String val=jTextField1.getText();
int t=0;
for(int i=0;i<val.length();i++){
    if(val.charAt(i)=='+' || val.charAt(i)=='-'){
        t++;
    }
}
//System.out.println("lengtrh of array"+t);
int[] k=new int[t];
String[] kl=new String[t+1];
int n=0;
for(int i=0;i<val.length();i++){
    if(val.charAt(i)=='+' || val.charAt(i)=='-'){
       
        k[n]=i;
        n++;
    }
 }


for(int i=0;i<k.length;i++){
    System.out.println(k[i]);
}

//
//int no=0;
//for(int i=0;i<kl.length;i++){
//    if(i==kl.length-1){
//        kl[i]=val.substring(no,val.length()-1);
//    }
//    kl[i]=val.substring(no,k[i]);
//    no=k[i]+1;
//}

if(t==1){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1));
}
if(t==2){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1));
}
if(t==3){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1,k[2]));
    System.out.print(val.charAt(k[2]));
    chai_rule(val.substring(k[2]+1));
}
if(t==4){
    chai_rule(val.substring(0,k[0]));
    System.out.print(val.charAt(k[0]));
    chai_rule(val.substring(k[0]+1,k[1]));
    System.out.print(val.charAt(k[1]));
    chai_rule(val.substring(k[1]+1,k[2]));
    System.out.print(val.charAt(k[2]));
    chai_rule(val.substring(k[2]+1,k[3]));
    System.out.print(val.charAt(k[3]));
    chai_rule(val.substring(k[3]+1));
}
//
//int no=0;
//for(int i=0;i<kl.length;i++){
//    kl[i]=val.substring(no,k[i]);
//    no=k[i]+1;
//    if(i==kl.length-1){
//    kl[i]=val.substring(k[i-1]+1);
//    //System.out.print("t"+t+"i"+i);
//    }
//}
//System.out.println("lets dee");

}
catch(Exception e){
    System.out.println(""+e);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diffrentiate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diffrentiate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diffrentiate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diffrentiate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diffrentiate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
